### ISSUE TITLE
Can't run the tool

### ISSUE THREAD

**Issue by karlitus** [kitykity/dowp#1]
Hello, 

I followed all the steps but when I run the bash file I get this message:

ls: /Users/krlts/dowp/dowpPosts/p*: No such file or directory

Any help?

Thanks!
Carlos

**Comment by kitykity** [comment]
Hi Carlos,
1. Do you have your wordpress.xml file in the /Users/krlts/dowp directory?
2. Is there anything in the /Users/krlts/dowp/dowpPosts/ directory--and does that directory exist?
3. If there is nothing in that directory... could you run the script like this and show me the output? 
   bash -x dowp.bash

Thanks  :)
Susan

**Comment by karlitus** [comment]
Hello!
1. Yes, I have my wordpress.xml file in the /Users/krlts/dowp directory
2. I didn't have the directory Users/krlts/dowp/dowpPosts/ created before.
   For this new test I created it and there was nothing in it.
3. This is the output:

ACMAC:dowp krlts$ bash -x dowp.bash

++ pwd
- thisDir=/Users/krlts/dowp
- postPopper
- rm /Users/krlts/dowp/dowpPosts/post. /Users/krlts/dowp/dowpPosts/post.0

++ ls '/Users/krlts/dowp/dowpPosts/p*'

ls: /Users/krlts/dowp/dowpPosts/p*: No such file or directory

ACMAC:dowp krlts$

So, still doesn't work... Any ideas?? Thanks for your help!!!

Carlos

On 9 February 2015 at 15:42, Susan notifications@github.com wrote:

> Hi Carlos,
> 
>    1.
> 
>    Do you have your wordpress.xml file in the /Users/krlts/dowp directory?
>    2.
> 
>    Is there anything in the /Users/krlts/dowp/dowpPosts/ directory--and
>    does that directory exist?
>    3.
> 
>    If there is nothing in that directory... could you run the script like
>    this and show me the output?
>    bash -x dowp.bash
> 
> Thanks :)
> Susan
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kitykity/dowp/issues/1#issuecomment-73530106.

## 

Carlos Miras Sepulveda
Digital Compositor
07894 6699 13  -   www.carlosmiras.com

**Comment by kitykity** [comment]
oh freaking duh. I am so sorry.

I'm looking at the code on the page... look at the last four lines...

## MAIN

#makePostFiles   # Create one file for each post.
postPopper      # Put posts into DayOne.

## END OF SCRIPT

Remove the comment (#) in front of makePostFiles. It's not making the post files... because I commented it out while I was testing.  :(

Sorry... and I'm glad you wrote to me, because I can fix this on the site now!

Please write back and let me know how it goes.

:)
Suzy

**Comment by kitykity** [comment]
(sorry... the markup made MAIN and END OF SCRIPT big. I wasn't barking at you. lol)

**Comment by karlitus** [comment]
haha thanks, I will try it tonight I'll let you know if it works!

Thanks!!

On 11 February 2015 at 16:41, Susan notifications@github.com wrote:

> (sorry... the markup made MAIN and END OF SCRIPT big. I wasn't barking at
> you. lol)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kitykity/dowp/issues/1#issuecomment-73914481.

## 

Carlos Miras Sepulveda
Junior Compositor / Digital Paint and Roto Artist
07894 6699 13  -   www.carlosmiras.com

**Comment by kitykity** [comment]
Rock on. I'm going to be off the grid for about a week, so if you have more
probs just drop me a message here and I'll get it when I get back online.

On Wed, Feb 11, 2015 at 10:49 AM, karlitus notifications@github.com wrote:

> haha thanks, I will try it tonight I'll let you know if it works!
> 
> Thanks!!
> 
> On 11 February 2015 at 16:41, Susan notifications@github.com wrote:
> 
> > (sorry... the markup made MAIN and END OF SCRIPT big. I wasn't barking at
> > you. lol)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kitykity/dowp/issues/1#issuecomment-73914481.
> 
> ## 
> 
> Carlos Miras Sepulveda
> Junior Compositor / Digital Paint and Roto Artist
> 07894 6699 13 - www.carlosmiras.com
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kitykity/dowp/issues/1#issuecomment-73916155.

## 

Susan Pitman
about.me/susan.a.pitman
[image: Susan Pitman on about.me]
  http://about.me/susan.a.pitman

**Comment by karlitus** [comment]
Hello!

It worked!! Thanks for your help!

Carlos

On 11 February 2015 at 16:53, Susan notifications@github.com wrote:

> Rock on. I'm going to be off the grid for about a week, so if you have more
> probs just drop me a message here and I'll get it when I get back online.
> 
> On Wed, Feb 11, 2015 at 10:49 AM, karlitus notifications@github.com
> wrote:
> 
> > haha thanks, I will try it tonight I'll let you know if it works!
> > 
> > Thanks!!
> > 
> > On 11 February 2015 at 16:41, Susan notifications@github.com wrote:
> > 
> > > (sorry... the markup made MAIN and END OF SCRIPT big. I wasn't barking
> > > at
> > > you. lol)
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/kitykity/dowp/issues/1#issuecomment-73914481.
> > 
> > ## 
> > 
> > Carlos Miras Sepulveda
> > Junior Compositor / Digital Paint and Roto Artist
> > 07894 6699 13 - www.carlosmiras.com
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kitykity/dowp/issues/1#issuecomment-73916155.
> 
> ## 
> 
> Susan Pitman
> about.me/susan.a.pitman
> [image: Susan Pitman on about.me]
> http://about.me/susan.a.pitman
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kitykity/dowp/issues/1#issuecomment-73917011.

## 

Carlos Miras Sepulveda
Digital Compositor
07894 6699 13  -   www.carlosmiras.com

**Comment by kitykity** [comment]
Yay! (so yeah I'm just getting back to this email LOL)

Glad you got it working :)

- Susan

On Fri, Feb 13, 2015 at 1:58 AM, karlitus <notifications@github.com> wrote:

> Hello!
>
> It worked!! Thanks for your help!
>
> Carlos
>
> On 11 February 2015 at 16:53, Susan <notifications@github.com> wrote:
>
> > Rock on. I'm going to be off the grid for about a week, so if you have
> more
> > probs just drop me a message here and I'll get it when I get back online.
> >
> > On Wed, Feb 11, 2015 at 10:49 AM, karlitus <notifications@github.com>
> > wrote:
> >
> > > haha thanks, I will try it tonight I'll let you know if it works!
> > >
> > > Thanks!!
> > >
> > > On 11 February 2015 at 16:41, Susan <notifications@github.com> wrote:
> > >
> > > > (sorry... the markup made MAIN and END OF SCRIPT big. I wasn't
> barking
> > at
> > > > you. lol)
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/kitykity/dowp/issues/1#issuecomment-73914481>.
> > > >
> > >
> > >
> > >
> > > --
> > > Carlos Miras Sepulveda
> > > Junior Compositor / Digital Paint and Roto Artist
> > > 07894 6699 13 - www.carlosmiras.com
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/kitykity/dowp/issues/1#issuecomment-73916155>.
> > >
> >
> >
> >
> > --
> >
> > Susan Pitman
> > about.me/susan.a.pitman
> > [image: Susan Pitman on about.me]
> > <http://about.me/susan.a.pitman>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kitykity/dowp/issues/1#issuecomment-73917011>.
> >
>
>
>
> --
> Carlos Miras Sepulveda
> Digital Compositor
> 07894 6699 13 - www.carlosmiras.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kitykity/dowp/issues/1#issuecomment-74217612>.
>



-- 

Susan Pitman
about.me/susan.a.pitman
[image: Susan Pitman on about.me]
  <http://about.me/susan.a.pitman>

**Comment by kitykity** [comment]
Awesome :) Let me know if you need anything else.
